% wecSimInputFile.m
% OSWEC input file for WEC-Sim MCR damping sweep.
%   1. Set dampingValues below.
%   2. Run: wecSimMCR

%% MCR Damping-Sweep Setup

project_folder = fileparts(mfilename('fullpath'));

% Base wave-condition file generated by Python/MHKiT.
% This can be either your array-style .mat or your wave-condition mcr .mat.
baseWaveMcrFile = fullfile(project_folder, 'wave_conditions', ...
    'wave_conditions_buoy_46050_2020_2021_2022_2023_2024_2025_16_clusters.mat');

% Runtime WEC-Sim-compatible MCR file.
runtimeMcrFile = fullfile(project_folder, 'wave_conditions', ...
    'oswec_runtime_damping_grid_mcr.mat');

% PTO damping values for the grid search.
% Change this line to change the damping sweep.
dampingValues = [1e4 1e5 1e6 1e7 1e8].';

% Build the runtime MCR file on the initial setup evaluation.
% During the actual MCR loop, variable mcr should already exist.
if ~exist('mcr', 'var') || ~isfield(mcr, 'cases')

    runtimeMcrFile = oswecBuildDampingMCR( ...
        baseWaveMcrFile, ...
        dampingValues, ...
        runtimeMcrFile);

    data = load(runtimeMcrFile, 'mcr');
    mcr = data.mcr;

end

% Determine current MCR case index.
% In WEC-Sim MCR, the loop variable is commonly imcr.
if exist('imcr', 'var')
    caseIndex = imcr;
elseif isfield(mcr, 'caseNum')
    caseIndex = mcr.caseNum;
else
    caseIndex = 1;
end

% Pull current case row from mcr.cases.
caseRow = mcr.cases(caseIndex, :);

% Column mapping:
caseNum       = caseRow(1);
conditionID   = caseRow(2);
waveID        = caseRow(3);
dampingID     = caseRow(4);
caseHm0       = caseRow(5);
caseTp        = caseRow(6);
caseTe        = caseRow(7);
caseProb      = caseRow(8);
caseDamping   = caseRow(9);

%% Simulation Data

simu = simulationClass();

% Use state-space radiation formulation
simu.stateSpace = 0;

simu.simMechanicsFile = 'OSWEC.slx';
simu.mode = 'normal';
simu.explorer = 'off';

% WEC-Sim-compatible MCR file
simu.mcrMatFile = runtimeMcrFile;

simu.startTime = 0;
simu.rampTime = 50;
simu.endTime = 400;

simu.solver = 'ode45';
simu.dt = 0.01;

simu.cicEndTime = 30;

%% Wave Information

waves = waveClass('irregular');

waves.height = caseHm0;                 % Significant wave height Hm0 [m]
waves.period = caseTp;                  % Peak period Tp [s]
waves.spectrumType = 'JS';              % JONSWAP spectrum

%% Body Data

body(1) = bodyClass('../_Common_Input_Files/OSWEC/hydroData/oswec.h5');
body(1).geometryFile = '../_Common_Input_Files/OSWEC/geometry/flap.stl';
body(1).mass = 127000;
body(1).inertia = [1.85e6 1.85e6 1.85e6];

body(2) = bodyClass('../_Common_Input_Files/OSWEC/hydroData/oswec.h5');
body(2).geometryFile = '../_Common_Input_Files/OSWEC/geometry/base.stl';
body(2).mass = 999;
body(2).inertia = [999 999 999];

%% PTO and Constraint Parameters

constraint(1) = constraintClass('Constraint1');
constraint(1).location = [0 0 -10];

pto(1) = ptoClass('PTO1');
pto(1).stiffness = 0;
pto(1).damping = caseDamping;
pto(1).location = [0 0 -8.9];

%% Console Output

fprintf('\n--------------------------------------------\n');
fprintf('OSWEC MCR damping-sweep case\n');
fprintf('MCR case number: %d\n', caseNum);
fprintf('Wave condition ID: %d\n', conditionID);
fprintf('Wave ID: %d\n', waveID);
fprintf('Damping ID: %d\n', dampingID);
fprintf('Hm0 = %.3f m\n', caseHm0);
fprintf('Tp = %.3f s\n', caseTp);
fprintf('Te = %.3f s\n', caseTe);
fprintf('Probability = %.5f\n', caseProb);
fprintf('PTO damping = %.3e\n', caseDamping);
fprintf('MCR file: %s\n', runtimeMcrFile);
fprintf('--------------------------------------------\n\n');