name: Run MATLAB tests on local changes
on:
  # Trigger the workflow on push or pull request,
  # but only for the github_actions branch
  push:
    branches:
      - github_actions
  pull_request:
    branches:
      - github_actions
jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release: [R2020a, latest]
        folder: [Body-to-Body_Interactions,
                 Desalination,
                 End_Stops,
                 Free_Decay,
                 Generalized_Body_Modes,
                 Mooring,
                 Multiple_Condition_Runs,
                 Nonhydro_Body,
                 Nonlinear_Hydro,
                 Paraview_Visualization,
                 Passive_Yaw,
                 PTO-Sim,
                 WECCCOMP_Fault_Implementation,
                 write_hdf5]
    name: ${{ matrix.folder }} on MATLAB ${{ matrix.release }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Check out WEC-Sim
        uses: actions/checkout@v2
        with:
          repository: H0R5E/WEC-Sim
          ref: 'disable_moorDynInput'
          path: './WEC-Sim'
      - name: Check out MoorDyn
        uses: actions/checkout@v2
        with:
          repository: WEC-Sim/MoorDyn
          path: './MoorDyn'
      - name: Copy MoorDyn Files
        run: |
            cp * ../WEC-Sim/source/functions/moorDyn
            ls ../WEC-Sim/source/functions/moorDyn
        shell: bash
        working-directory: './MoorDyn'
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v1
      - name: Install WEC-Sim
        uses: matlab-actions/run-command@v1
        with:
          command: addpath(genpath('WEC-Sim/source'));, savepath pathdef.m;
      - name: Run tests and generate artifacts
        uses: matlab-actions/run-command@v1
        with:
          command: results = wecSimAppTest("${{ matrix.folder }}"), assertSuccess(results);
